name: Test IPython beamline profiles

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string

jobs:
  testing_beamline_profiles:
    name: ${{ matrix.repos.beamline_acronym }}-${{ matrix.repos.repo }}-${{ matrix.repos.branch }}-py311
    env:
      REPO_URL: "https://github.com/${{ matrix.repos.org }}/${{ matrix.repos.repo }}"
    strategy:
      fail-fast: false
      matrix:
        repos:
          - org: "NSLS-II-AMX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "amx"
          - org: "NSLS-II-BMM"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "bmm"
          - org: "NSLS-II-CHX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "chx"
          # TODO: revert the CMS config once the PR is merged:
          - org: "thomashopkins32"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "cms"
          # - org: "NSLS-II-CMS"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline_acronym: "cms"
          - org: "NSLS-II-CSX"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "csx"
          - org: "NSLS-II-ESM-1"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "arpes"
          - org: "NSLS-II-ESM-2"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "xpeem"
          - org: "NSLS-II-FMX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "fmx"
          - org: "NSLS-II-FXI"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "fxi"
          - org: "NSLS-II-HEX"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "hex"
          - org: "NSLS-II-HXN"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "hxn"
          - org: "NSLS-II-IOS"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "ios"
          - org: "NSLS-II-IXS"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "ixs"
          - org: "NSLS-II-ISR"
            repo: "profile_D-hutch"
            branch: "main"
            beamline_acronym: "isr"
          # - org: "NSLS-II-ISR"
          #   repo: "profile_analysis"
          #   branch: "master"
          #   beamline_acronym: "isr"
          - org: "NSLS-II-LIX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "lix"
          - org: "NSLS-II-NYX"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "nyx"
          - org: "NSLS-II-QAS"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "qas"
          - org: "NSLS-II-PDF"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "pdf"
          - org: "NSLS-II-SIX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "six"
          - org: "NSLS-II-SMI"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "smi"
          - org: "NSLS-II-SRX"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "srx"
          - org: "NSLS-II-TES"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "tes"
          - org: "NSLS-II-TST"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "tst"
          - org: "NSLS-II-SST"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "sst"
          - org: "NSLS-II-SST"
            repo: "profile_collection_ucal"
            branch: "master"
            beamline_acronym: "sst"
          - org: "NSLS-II-SST"
            repo: "profile_collection_haxpes"
            branch: "master"
            beamline_acronym: "sst"
          - org: "NSLS-II-XFM"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "xfm"
          - org: "NSLS-II-XFP"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "xfp"
          - org: "NSLS-II-XPD"
            repo: "profile_collection"
            branch: "master"
            beamline_acronym: "xpd"
          - org: "NSLS-II-XPD-tomo"
            repo: "profile_collection"
            branch: "main"
            beamline_acronym: "xpdd"

    runs-on: ubuntu-latest
    steps:
      - name: using test-action
        uses: NSLS2/gha-beamline-integration-test@2025-1.0-test
        with:
          conda_env_url: "https://zenodo.org/records/14862443/files/2025-1.0-py311-tiled.tar.gz"
          conda_env_md5: "3b1074c0827ee3baf0cdcd64917b9afa"
          org: "${{ matrix.repos.org }}"
          repo: "${{ matrix.repos.repo }}"
          branch: "${{ matrix.repos.branch }}"
          beamline-acronym: "${{ matrix.repos.beamline_acronym }}"
